Added a dark mode that works with OS preference
boratanrikulu/lirik.app pull request #14
Opened 2021-01-18 19:58 UTC by ardaa

Added a dark mode using JS, HTML, and pure CSS. Works then prefers-color-scheme is 'dark'. Some package cleanup may be necessary as I installed some modules and wasn't able to purge them with my limited Golang knowledge. Also fixed an error typo.
TODO:
Add a toggle button that toggles between dark and light mode and bypassing OS preference

2021-01-18 20:24 UTC, boratanrikulu commented
Hi,
Thank you for your contribution!   
I believe toggle buttons is a must for this feature. We should add it too.  
Can we improve dark theme style? It may be seem much better.

PR:
![Screenshot_2021-01-18_23-06-43](https://user-images.githubusercontent.com/20258973/104959429-3a919600-59e3-11eb-9a8c-16d080f7ab3b.png)

Auto dark-reader theme is a good example:
![Screenshot_2021-01-18_23-20-01](https://user-images.githubusercontent.com/20258973/104959845-2bf7ae80-59e4-11eb-8326-56db1d116539.png)

2021-01-18 20:28 UTC, boratanrikulu commented on go.mod
> +	gopkg.in/ini.v1 v1.62.0 // indirect
I think not necessary these lines.

2021-01-18 20:28 UTC, boratanrikulu commented on go.mod.save
> +:q
This file must be deleted.

2021-01-18 20:29 UTC, boratanrikulu commented on go.sum
> +cloud.google.com/go v0.26.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
There's no need to change go.sum.

2021-01-18 20:30 UTC, boratanrikulu commented on go.sum
> +cloud.google.com/go v0.26.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
Most of these packages are not used at Lirik.app

2021-01-18 20:32 UTC, ardaa commented
Cool. Changing the color scheme to look like the image above. Sadly, I wasn't able to toggle the colors without using a CSS preprocessor or a bad JS hack. I really don't know Go so leaving that to other coders.

2021-01-18 20:32 UTC, boratanrikulu requested changes
Some changes are needed.

2021-01-18 20:35 UTC, boratanrikulu commented
> Cool. Changing the color scheme to look like the image above. Sadly, I wasn't able to toggle the colors without using a CSS preprocessor or a bad JS hack. I really don't know Go so leaving that to other coders.

That's okay. We can open another issue for toggle button.  
For now, I will wait an update from you for css improvements and deleting unneeded commits(like changing go.mod or go.sum files).

2021-01-18 20:37 UTC, boratanrikulu commented
Thank you again.  
I'll add an documentation to how to set-up the application on a local device.  
It's great to see you figure out that yourself.

2021-01-18 20:55 UTC, ardaa commented
> Thank you again.
> I'll add an documentation to how to set-up the application on a local device.
> It's great to see you figure out that yourself.

I can also write the documentation on the setup process if you want.

2021-01-18 21:06 UTC, ardaa commented
<img width="1440" alt="Screen Shot 2021-01-18 at 11 51 54 PM" src="https://user-images.githubusercontent.com/6864260/104962764-2d2bda00-59ea-11eb-9c43-1ac325142efd.png">
Looks like this right now.

2021-01-19 09:58 UTC, boratanrikulu commented
> <img alt="Screen Shot 2021-01-18 at 11 51 54 PM" width="1440" src="https://user-images.githubusercontent.com/6864260/104962764-2d2bda00-59ea-11eb-9c43-1ac325142efd.png">
> Looks like this right now.

Hi,  
Seems much better! Could you do set tab titles to white and set `<hr>` style just like on the screenshot that sent by me?

2021-01-19 10:00 UTC, boratanrikulu commented
> > Thank you again.
> > I'll add an documentation to how to set-up the application on a local device.
> > It's great to see you figure out that yourself.
> 
> I can also write the documentation on the setup process if you want.

Handling documentation by me much be better, thank you for offer.

2021-01-19 10:33 UTC, aykutkardas commented
I think it has a lot of change. You can keep this simpler. For example using css variables. @ardaa 

```css
:root {
  --background: white;
  --foreground: black;
}

[data-theme='dark'] {
  --background: black;
  --foreground: white;
}
```

2021-10-09 22:34 UTC, boratanrikulu commented
Kendimce bir koyu görünüm ekledim, bu pr'ı kapatıyorum
desteklerin için teşekkür ederim @ardaa 

![](https://raw.githubusercontent.com/boratanrikulu/lirik.app/main/example.png)

2021-10-09 22:34 UTC, closed without merging